/* eslint-disable */
export default {
  "key": "i9events",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "book_inspection": "Book Inspection",
        "book_inspection_title": "Book Boat Inspection",
        "boat_name": "Boat Name",
        "boat_owner": "Owner",
        "location": "Location",
        "date": "Date",
        "time": "Time",
        "cancel": "Cancel",
        "book": "Book",
        "register_as": "Register as Inspector",
        "register_title": "Register as Boat Inspector",
        "register": "Register",
        "inspection_date": "Inspection Date",
        "start_time": "Start Time",
        "end_time": "End Time",
        "inspector": "Inspector",
        "inspectors": "Nr inspectors",
        "boats": "Nr boats",
        "create_title": "Create New Inspection Event",
        "reset": "Reset",
        "back": "Back",
        "next": "Next",
        "finish": "Finish",
        "location_required": "Location is Required",
        "date_required": "Inspection Date is Required",
        "start_time_required": "Start Time is Required",
        "end_time_required": "End Time is Required",
        "start_before_end": "End Time must be after Start Time"
      },
      "fi-FI": {
        "book_inspection": "Varaa katsastus",
        "book_inspection_title": "Varaa veneen katsastus",
        "boat_name": "Veneen nimi",
        "boat_owner": "Omistaja",
        "location": "Paikka",
        "date": "Päivä",
        "time": "Aika",
        "cancel": "Peru",
        "book": "Varaa",
        "register_as": "Ilmoittaudu katsastajaksi",
        "register_title": "Ilmoittaudu katsastajaksi",
        "register": "Ilmoittaudu",
        "inspection_date": "Päivämäärä",
        "start_time": "Alkaa klo",
        "end_time": "Päättyy klo",
        "inspector": "Katsastaja",
        "inspectors": "Katsastajien lkm",
        "boats": "Veneiden lkm",
        "create_title": "Tee uusi katsastustapahtuma",
        "reset": "Palauta",
        "back": "Takaisin",
        "next": "Seuraava",
        "finish": "Päätä",
        "location_required": "Paikka on annettava",
        "date_required": "Päivämäärä on annettava",
        "start_time_required": "Aloitusaika on annettava",
        "end_time_required": "Päätösaika on annettava",
        "start_before_end": "Päätösajan on oltava aloitusajan jälkeen"
      },
      "sv-FI": {
        "book_inspection": "Boka besiktning",
        "book_inspection_title": "Boka båtbesiktning",
        "boat_name": "Båtens  namn",
        "boat_owner": "Ägare",
        "location": "Plats",
        "date": "Datum",
        "time": "Tid",
        "cancel": "Avbryt",
        "book": "Boka",
        "register_as": "Anmäl dig som besiktningsman",
        "register_title": "Anmäl dig som besiktningsman",
        "register": "Anmäl dig",
        "inspection_date": "Datum",
        "start_time": "Börjar kl",
        "end_time": "Slutar kl",
        "inspector": "Besiktningsman",
        "inspectors": "Antal besiktningsmän",
        "boats": "Antal båtar",
        "create_title": "Skapa nytt besiktningstillfälle",
        "reset": "Återställ",
        "back": "Föregående",
        "next": "Följande",
        "finish": "Avsluta",
        "location_required": "Plats måste anges",
        "date_required": "Datum måste anges",
        "start_time_required": "Start måste anges",
        "end_time_required": "Avslutning måste anges",
        "start_before_end": "Avslutning måste vara efter start"
      }
    }
  },
  "localIds": [
    "i9events::local::src/inspectionevents/i9events.content.ts"
  ]
} as const;
