/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OfficeRouteRouteImport } from './routes/office.route'
import { Route as I9eventRouteRouteImport } from './routes/i9event.route'
import { Route as DispatchRouteRouteImport } from './routes/dispatch.route'
import { Route as BoatsRouteRouteImport } from './routes/boats.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspectIndexRouteImport } from './routes/inspect.index'
import { Route as InspectInspectionIdRouteImport } from './routes/inspect.$inspectionId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRouteRoute = OfficeRouteRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const I9eventRouteRoute = I9eventRouteRouteImport.update({
  id: '/i9event',
  path: '/i9event',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRouteRoute = DispatchRouteRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const BoatsRouteRoute = BoatsRouteRouteImport.update({
  id: '/boats',
  path: '/boats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectIndexRoute = InspectIndexRouteImport.update({
  id: '/inspect/',
  path: '/inspect/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectInspectionIdRoute = InspectInspectionIdRouteImport.update({
  id: '/inspect/$inspectionId',
  path: '/inspect/$inspectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boats': typeof BoatsRouteRoute
  '/dispatch': typeof DispatchRouteRoute
  '/i9event': typeof I9eventRouteRoute
  '/office': typeof OfficeRouteRoute
  '/about': typeof AboutRoute
  '/inspect/$inspectionId': typeof InspectInspectionIdRoute
  '/inspect': typeof InspectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boats': typeof BoatsRouteRoute
  '/dispatch': typeof DispatchRouteRoute
  '/i9event': typeof I9eventRouteRoute
  '/office': typeof OfficeRouteRoute
  '/about': typeof AboutRoute
  '/inspect/$inspectionId': typeof InspectInspectionIdRoute
  '/inspect': typeof InspectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boats': typeof BoatsRouteRoute
  '/dispatch': typeof DispatchRouteRoute
  '/i9event': typeof I9eventRouteRoute
  '/office': typeof OfficeRouteRoute
  '/about': typeof AboutRoute
  '/inspect/$inspectionId': typeof InspectInspectionIdRoute
  '/inspect/': typeof InspectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boats'
    | '/dispatch'
    | '/i9event'
    | '/office'
    | '/about'
    | '/inspect/$inspectionId'
    | '/inspect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boats'
    | '/dispatch'
    | '/i9event'
    | '/office'
    | '/about'
    | '/inspect/$inspectionId'
    | '/inspect'
  id:
    | '__root__'
    | '/'
    | '/boats'
    | '/dispatch'
    | '/i9event'
    | '/office'
    | '/about'
    | '/inspect/$inspectionId'
    | '/inspect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoatsRouteRoute: typeof BoatsRouteRoute
  DispatchRouteRoute: typeof DispatchRouteRoute
  I9eventRouteRoute: typeof I9eventRouteRoute
  OfficeRouteRoute: typeof OfficeRouteRoute
  AboutRoute: typeof AboutRoute
  InspectInspectionIdRoute: typeof InspectInspectionIdRoute
  InspectIndexRoute: typeof InspectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i9event': {
      id: '/i9event'
      path: '/i9event'
      fullPath: '/i9event'
      preLoaderRoute: typeof I9eventRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boats': {
      id: '/boats'
      path: '/boats'
      fullPath: '/boats'
      preLoaderRoute: typeof BoatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/': {
      id: '/inspect/'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof InspectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$inspectionId': {
      id: '/inspect/$inspectionId'
      path: '/inspect/$inspectionId'
      fullPath: '/inspect/$inspectionId'
      preLoaderRoute: typeof InspectInspectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoatsRouteRoute: BoatsRouteRoute,
  DispatchRouteRoute: DispatchRouteRoute,
  I9eventRouteRoute: I9eventRouteRoute,
  OfficeRouteRoute: OfficeRouteRoute,
  AboutRoute: AboutRoute,
  InspectInspectionIdRoute: InspectInspectionIdRoute,
  InspectIndexRoute: InspectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
