/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InspectRouteRouteImport } from './routes/inspect.route'
import { Route as BoatsRouteRouteImport } from './routes/boats.route'
import { Route as IndexRouteImport } from './routes/index'

const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectRouteRoute = InspectRouteRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const BoatsRouteRoute = BoatsRouteRouteImport.update({
  id: '/boats',
  path: '/boats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boats': typeof BoatsRouteRoute
  '/inspect': typeof InspectRouteRoute
  '/about': typeof AboutRoute
  '/dispatch': typeof DispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boats': typeof BoatsRouteRoute
  '/inspect': typeof InspectRouteRoute
  '/about': typeof AboutRoute
  '/dispatch': typeof DispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boats': typeof BoatsRouteRoute
  '/inspect': typeof InspectRouteRoute
  '/about': typeof AboutRoute
  '/dispatch': typeof DispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boats' | '/inspect' | '/about' | '/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boats' | '/inspect' | '/about' | '/dispatch'
  id: '__root__' | '/' | '/boats' | '/inspect' | '/about' | '/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoatsRouteRoute: typeof BoatsRouteRoute
  InspectRouteRoute: typeof InspectRouteRoute
  AboutRoute: typeof AboutRoute
  DispatchRoute: typeof DispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect': {
      id: '/inspect'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof InspectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boats': {
      id: '/boats'
      path: '/boats'
      fullPath: '/boats'
      preLoaderRoute: typeof BoatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoatsRouteRoute: BoatsRouteRoute,
  InspectRouteRoute: InspectRouteRoute,
  AboutRoute: AboutRoute,
  DispatchRoute: DispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
