DROP TABLE IF EXISTS boats;
DROP INDEX IF EXISTS idx_boats_name;
DROP INDEX IF EXISTS idx_boats_owner;
DROP INDEX IF EXISTS idx_boats_make;
DROP INDEX IF EXISTS idx_boats_created_at;

CREATE TABLE boats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    sign VARCHAR(50),
    make VARCHAR(50),
    model VARCHAR(50),
    loa FLOAT,
    draft FLOAT,
    beam FLOAT,
    deplacement FLOAT,
    engines VARCHAR(50),
    year VARCHAR(4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(50) NOT NULL,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(50),
    version INT NOT NULL
);

ALTER SEQUENCE boats_id_seq RESTART WITH 1001;

CREATE INDEX idx_boats_name ON boats(name);
CREATE INDEX idx_boats_owner ON boats(owner);
CREATE INDEX idx_boats_make ON boats(make);
CREATE INDEX idx_boats_created_at ON boats(created_at);
