DROP TABLE IF EXISTS i9events;
DROP INDEX IF EXISTS idx_i9events_place;
DROP INDEX IF EXISTS idx_i9events_starts;

CREATE TABLE i9events (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	place varchar(255) NOT NULL,
	starts timestamptz NOT NULL,
	ends timestamptz NOT NULL,
	boats _varchar NULL,
	inspectors _varchar NULL,
	created_at timestamptz NULL,
	created_by varchar(255) NULL,
	modified_at timestamptz NULL,
	modified_by varchar(255) NULL,
	"version" int4 NOT NULL,
	CONSTRAINT i9events_pkey PRIMARY KEY (id)
);

ALTER SEQUENCE i9events_id_seq RESTART WITH 1001;

CREATE INDEX idx_i9events_place ON i9events(place);
CREATE INDEX idx_i9events_starts ON i9events(starts);
