DROP TABLE IF EXISTS inspections;
DROP INDEX IF EXISTS idx_inspections_place;
DROP TABLE IF EXISTS inspection_data;
DROP TABLE IF EXISTS hull_data;
DROP TABLE IF EXISTS rig_data;
DROP TABLE IF EXISTS engine_data;

CREATE TABLE inspections (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1001 MAXVALUE 8999999999999999999 START 1001 CACHE 1 NO CYCLE) NOT NULL,
	"timestamp" timestamptz(6) NULL,
	inspector varchar(255) NOT NULL,
	boat int8 NOT NULL,
	"event" int8 NOT NULL,
	completed timestamptz(6) NULL,
	created_at timestamptz(6) NULL,
	created_by varchar(255) NULL,
	modified_at timestamptz(6) NULL,
	modified_by varchar(255) NULL,
	"version" int4 NOT NULL,
	CONSTRAINT inspections_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_inspections_inspector ON inspections USING btree (inspector);

CREATE TABLE inspection_data (
	inspections int8 NOT NULL
);

CREATE TABLE hull_data (
	inspections int8 NOT NULL,
	hull bool NULL,
	openings bool NULL,
	material bool NULL,
	keel_rudder bool null,
	steering bool NULL,
	drive_shaft_prop bool NULL,
	throughulls bool NULL,
	fall_protection bool NULL,
  	heavy_objects bool NULL,
  	fresh_water bool NULL,
  	lowest_leak int NULL
);

CREATE TABLE rig_data (
	inspections int8 NOT NULL,
	rig bool NULL,
	sails bool NULL,
	storm_sails bool NULL,
	reefing bool NULL
);

CREATE TABLE engine_data (
	inspections int8 NOT NULL,
	installation bool NULL,
	controls bool NULL,
	fuel_system bool NULL,
  	cooling bool NULL,
  	strainer bool NULL,
  	separate_batteries bool NULL,
  	shore_power bool NULL,
  	"aggregate" bool NULL
);

CREATE TABLE equipment_data (
	inspections int8 NOT NULL,
	markings bool NULL,
  	anchors bool NULL,
  	sea_anchor bool NULL,
  	lines int NULL,
  	tools bool NULL,
  	paddel bool NULL,
  	hook bool NULL,
  	resque_line bool NULL,
  	fenders bool NULL,
  	ladders bool NULL,
  	defroster bool NULL,
  	toilet bool NULL,
  	gas_system bool NULL,
  	stove bool NULL,
  	flag bool null
);

CREATE TABLE maritime_data (
	inspections int8 NOT NULL,
	lights bool NULL,
  	dayshapes bool NULL,
  	horn bool NULL,
  	reflector bool NULL,
  	compass bool NULL,
  	bearing bool NULL,
  	log bool NULL,
  	charts bool NULL,
  	radio bool NULL,
  	satnav bool NULL,
  	radar bool NULL,
  	spotlight bool NULL,
  	vhf bool NULL,
  	hand_vhf bool NULL,
  	documents bool NULL
);

CREATE TABLE safety_data (
	inspections int8 NOT NULL,
	buoyancy bool NULL,
  	harness int NULL,
  	lifebuoy int NULL,
  	signals_a bool NULL,
  	signals_b bool NULL,
  	fixed_handpump int NULL,
  	electric_pump bool NULL,
  	hand_extinguisher int NULL,
  	fire_blanket bool NULL,
  	plugs bool NULL,
  	flashlight int NULL,
  	firstaid bool NULL,
  	spare_steering bool NULL,
  	emergency_tools bool NULL,
  	reserves bool NULL,
  	liferaft bool NULL,
  	detector bool NULL
);
