import { BoatType } from "./boat";

export const boats: Array<BoatType> = [
  {
    boatId: '1',
    name: "BoatName",
    sign: "Sign123",
    make: "MakeX",
    model: "ModelY",
    loa: 10.5,
    draft: 2.5,
    beam: 3.5,
    deplacement: 5000.0,
    owner: "OwnerName",
    engines: "VP",
    year: "1997",
  },
  {
    boatId: '2',
    name: "AnotherBoat",
    sign: "Sign456",
    make: "MakeA",
    model: "ModelB",
    loa: 12.0,
    draft: 3.0,
    beam: 4.0,
    deplacement: 6000.0,
    owner: "AnotherOwner",
    engines: "VP",
    year: "1997",
  },
  {
    boatId: '3',
    name: "ThirdBoat",
    sign: "Sign789",
    make: "MakeC",
    model: "ModelD",
    loa: 15.0,
    draft: 4.0,
    beam: 5.0,
    deplacement: 7000.0,
    owner: "ThirdOwner",
    engines: "VP",
    year: "1997",
  },
  {
    boatId: '4',
    name: "FourthBoat",
    sign: "Sign012",
    make: "MakeE",
    model: "ModelF",
    loa: 20.0,
    draft: 5.0,
    beam: 6.0,
    deplacement: 8000.0,
    owner: "FourthOwner",
    engines: "VP",
    year: "1997",
  },
  {
    boatId: '5',
    name: "FifthBoat",
    sign: "Sign345",
    make: "MakeG",
    model: "ModelH",
    loa: 25.0,
    draft: 6.0,
    beam: 7.0,
    deplacement: 9000.0,
    owner: "FifthOwner",
    engines: "VP",
    year: "1997",
  },
];

