DROP TABLE IF EXISTS boats;
DROP INDEX IF EXISTS idx_boats_created_at;
DROP INDEX IF EXISTS idx_boats_make;
DROP INDEX IF EXISTS idx_boats_name;
DROP INDEX IF EXISTS idx_boats_owner;

DROP TABLE IF EXISTS i9events;
DROP INDEX IF EXISTS idx_i9events_place;
DROP INDEX IF EXISTS idx_i9events_starts;

DROP TABLE IF EXISTS boat_bookings;
DROP TABLE IF EXISTS inspector_registrations;

CREATE TABLE boats (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1001 MAXVALUE 8999999999999999999 START 1001 CACHE 1 NO CYCLE) NOT NULL,
	"owner" varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	sign varchar(50) NULL,
	make varchar(50) NULL,
	model varchar(50) NULL,
	loa float8 NULL,
	draft float8 NULL,
	beam float8 NULL,
	deplacement float8 NULL,
	engines varchar(50) NULL,
	"year" varchar(4) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_by varchar(50) NOT NULL,
	modified_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	modified_by varchar(50) NULL,
	"version" int4 NOT NULL,
	CONSTRAINT boats_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_boats_created_at ON public.boats USING btree (created_at);
CREATE INDEX idx_boats_make ON public.boats USING btree (make);
CREATE INDEX idx_boats_name ON public.boats USING btree (name);
CREATE INDEX idx_boats_owner ON public.boats USING btree (owner);

CREATE TABLE i9events (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1001 MAXVALUE 8999999999999999999 START 1001 CACHE 1 NO CYCLE) NOT NULL,
	place varchar(255) NOT NULL,
	starts timestamptz NOT NULL,
	ends timestamptz NOT NULL,
	created_at timestamptz NULL,
	created_by varchar(255) NULL,
	modified_at timestamptz NULL,
	modified_by varchar(255) NULL,
	"version" int4 NOT NULL,
	CONSTRAINT i9events_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_i9events_place ON public.i9events USING btree (place);
CREATE INDEX idx_i9events_starts ON public.i9events USING btree (starts);

CREATE TABLE inspector_registrations (
	i9events int8 NULL,
	inspector_name varchar(255) NOT NULL,
	message varchar(255) NULL,
	created_at timestamptz NULL,
	created_by varchar(255) NULL
);

CREATE TABLE boat_bookings (
	i9events int8 NULL,
	boat_name varchar(255) NOT NULL,
	message varchar(255) NULL,
	created_at timestamptz NULL,
	created_by varchar(255) NULL
);
