DROP TABLE IF EXISTS boats;
DROP INDEX IF EXISTS idx_boats_created_at;
DROP INDEX IF EXISTS idx_boats_make;
DROP INDEX IF EXISTS idx_boats_name;
DROP INDEX IF EXISTS idx_boats_owner;

DROP TABLE IF EXISTS i9events;
DROP INDEX IF EXISTS idx_i9events_place;
DROP INDEX IF EXISTS idx_i9events_starts;

DROP TABLE IF EXISTS boat_bookings;
DROP TABLE IF EXISTS inspector_registrations;

DROP TABLE IF EXISTS inspections;
DROP TABLE IF EXISTS inspection_data;
DROP TABLE IF EXISTS hull_data;
DROP TABLE IF EXISTS rig_data;
DROP TABLE IF EXISTS engine_data;

CREATE TABLE boats (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1001 MAXVALUE 8999999999999999999 START 1001 CACHE 1 NO CYCLE) NOT NULL,
	"owner" varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	sign varchar(50) NULL,
	make varchar(50) NULL,
	model varchar(50) NULL,
	loa float8 NULL,
	draft float8 NULL,
	beam float8 NULL,
	deplacement float8 NULL,
	engines varchar(50) NULL,
	"year" varchar(4) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_by varchar(50) NOT NULL,
	modified_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	modified_by varchar(50) NULL,
	"version" int4 NOT NULL,
	CONSTRAINT boats_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_boats_created_at ON boats USING btree (created_at);
CREATE INDEX idx_boats_make ON boats USING btree (make);
CREATE INDEX idx_boats_name ON boats USING btree (name);
CREATE INDEX idx_boats_owner ON boats USING btree (owner);

CREATE TABLE i9events (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1001 MAXVALUE 8999999999999999999 START 1001 CACHE 1 NO CYCLE) NOT NULL,
	place varchar(255) NOT NULL,
	starts timestamptz NOT NULL,
	ends timestamptz NOT NULL,
	created_at timestamptz NULL,
	created_by varchar(255) NULL,
	modified_at timestamptz NULL,
	modified_by varchar(255) NULL,
	"version" int4 NOT NULL,
	CONSTRAINT i9events_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_i9events_place ON i9events USING btree (place);
CREATE INDEX idx_i9events_starts ON i9events USING btree (starts);

CREATE TABLE inspector_registrations (
	i9events int8 NULL,
	inspector_name varchar(255) NOT NULL,
	message varchar(255) NULL,
	created_at timestamptz NULL,
	created_by varchar(255) NULL
);

CREATE TABLE boat_bookings (
	i9events int8 NULL,
	boat_id int8 NOT NULL,
	message varchar(255) NULL,
	taken bool DEFAULT false NULL,
	created_at timestamptz NULL,
	created_by varchar(255) NULL
);

CREATE TABLE inspections (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1001 MAXVALUE 8999999999999999999 START 1001 CACHE 1 NO CYCLE) NOT NULL,
	"timestamp" timestamptz(6) NULL,
	inspector varchar(255) NOT NULL,
	boat int8 NOT NULL,
	"event" int8 NOT NULL,
	completed timestamptz(6) NULL,
	created_at timestamptz(6) NULL,
	created_by varchar(255) NULL,
	modified_at timestamptz(6) NULL,
	modified_by varchar(255) NULL,
	"version" int4 NOT NULL,
	CONSTRAINT inspections_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_inspections_inspector ON inspections USING btree (inspector);

CREATE TABLE inspection_data (
	inspections int8 NOT NULL
);

CREATE TABLE hull_data (
	inspections int8 NOT NULL,
	hull bool NULL,
	openings bool NULL,
	material bool NULL,
	keel_rudder bool null,
	steering bool NULL,
	drive_shaft_prop bool NULL,
	throughulls bool NULL,
	fall_protection bool NULL,
  	heavy_objects bool NULL,
  	fresh_water bool NULL,
  	lowest_leak int NULL
);

CREATE TABLE rig_data (
	inspections int8 NOT NULL,
	rig bool NULL,
	sails bool NULL,
	storm_sails bool NULL,
	reefing bool NULL
);

CREATE TABLE engine_data (
	inspections int8 NOT NULL,
	installation bool NULL,
	controls bool NULL,
	fuel_system bool NULL,
  	cooling bool NULL,
  	strainer bool NULL,
  	separate_batteries bool NULL,
  	shore_power bool NULL,
  	"aggregate" bool NULL
);
