DROP TABLE IF EXISTS boats;
CREATE TABLE boats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    sign VARCHAR(50),
    make VARCHAR(50),
    model VARCHAR(50),
    loa FLOAT,
    draft FLOAT,
    beam FLOAT,
    deplacement FLOAT,
    engines VARCHAR(50),
    year VARCHAR(4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(50) NOT NULL,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(50),
    version INT NOT NULL
);

ALTER SEQUENCE boats_id_seq RESTART WITH 1001;

CREATE INDEX idx_boats_name ON boats(name);
CREATE INDEX idx_boats_owner ON boats(owner);
CREATE INDEX idx_boats_make ON boats(make);
CREATE INDEX idx_boats_created_at ON boats(created_at);

INSERT INTO boats (owner, name, sign, make, model, loa, draft, beam, deplacement, engines, year, created_at, created_by, modified_at, modified_by, version) VALUES
('stina', 'Wave Rider', 'WR5678', 'Kawasaki', 'Ultra LX', 3.35, 0.76, 1.14, 320, 'Kawasaki 1.5L', '2019', CURRENT_TIMESTAMP, 'bob', CURRENT_TIMESTAMP, 'stina', 1),
('ronja', 'Ocean Explorer', 'OE9101', 'Sea-Doo', 'GTX Limited', 3.51, 0.84, 1.20, 340, 'Rotax 1.6L', '2021', CURRENT_TIMESTAMP, 'charlie', CURRENT_TIMESTAMP, 'ronja', 1),
('diana', 'River Runner', 'RR1122', 'Honda', 'AquaTrax F-12X', 3.30, 0.75, 1.10, 300, 'Honda 1.4L', '2018', CURRENT_TIMESTAMP, 'diana', CURRENT_TIMESTAMP, 'diana', 1),
('ronja', 'Lake Cruiser', 'LC3344', 'Polaris', 'SLX 1500', 3.40, 0.80, 1.15, 310, 'Polaris 1.5L', '2022', CURRENT_TIMESTAMP, 'edward', CURRENT_TIMESTAMP, 'stina', 1),
('fiona', 'Sun Chaser', 'SC5566', 'Yamaha', 'VX Deluxe', 3.25, 0.78, 1.12, 290, 'Yamaha 1.3L', '2017', CURRENT_TIMESTAMP, 'fiona', CURRENT_TIMESTAMP, 'fiona', 1);
